### ISSUE TITLE
Missing Fork

### ISSUE THREAD

**Issue by aleLanda-rq** [learn-co-curriculum/phase-0-configuring-the-flatiron-student-portal#15]
### Canvas Link

https://learning.flatironschool.com/courses/5461/pages/configuring-the-flatiron-student-portal?module_item_id=353219

### Concern

Hello! I do not see a "fork" button on the right hand side.
![image](https://user-images.githubusercontent.com/98127121/150584538-e0bdf2a5-55d8-4bc1-a01a-9146421cd96f.png)

**Comment by graciemcguire** [comment]
Hi @aleLanda-rq !
The fork button will only appear in lessons where you need to use the lesson's repository to complete your work. In this lesson, you will be setting up your local environment, so no repository is necessary.

Happy coding! 💙
