### ISSUE TITLE
Learn whoami

### ISSUE THREAD

**Issue by Jamesbot89** [learn-co-curriculum/phase-0-configuring-the-flatiron-student-portal#18]
### Canvas Link

https://learning.flatironschool.com/courses/5274/pages/configuring-the-flatiron-student-portal?module_item_id=353827

### Concern

When I type in "learn whoami" it states "learn: command not found." So it doesn't allow me to paste my token.

**Comment by AlveeM** [comment]
What errors did you get when you ran `gem install learn-co`?

If the gem isn't installed correctly you'll get the "learn: command not found" error.

**Comment by AlveeM** [comment]
I'm closing this issue for now. If you still have any questions or follow-up, please feel free to reopen this issue or submit a new one.
