### ISSUE TITLE
username incorrect?

### ISSUE THREAD

**Issue by amawalke** [learn-co-curriculum/phase-0-configuring-the-flatiron-student-portal#24]
when I configured my learn-co gem and copied and pasted my oath token, then put whoami in the terminal, my name and email were correct (Manny Walker, surfingislife82@yahoo.com) but my username came up as jovial-actor-4c2a. Is this a default username? I thought that my username was amawalke. Please advise.

**Comment by lizbur10** [comment]
Hi @amawalke ! I believe the `learn-co` gem does generate a username when you configure your account, but it shouldn't affect you - you should be able to use `amawalke`. If you're having any problems with it, your best bet is to use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team. 💙
