### ISSUE TITLE
Forking this assignmet

### ISSUE THREAD

**Issue by Anedwards180** [learn-co-curriculum/phase-0-configuring-the-flatiron-student-portal#4]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

Add a link to the assignment in Canvas here.

## What should be changed?

Suggest your change here. Let us know what section or line of the Readme needs
to be updated, and any proposed corrections. Include the line number(s) if
possible.

Hello! I found this assignment to very difficult, because I forked it in the beginning. My normal process to doing the modules is to fork first, set up my environment, and then dive in. I read this lesson several times over and was still very confused about the objectives and how my work would be submitted. Had I known that it would be automatically forked for me after completing the necessary steps would have been very helpful.  .  My suggestion for this lesson is to possibly put in a message at the top in big bright font to "hold off on forking until later instructed to do so with the lesson," and then give some information from the start about how when completed the work will be submitted and completed automatically through running learn test.

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the GitHub repo and believe your issue to have been resolved. Note, however, that if you are working in Canvas the changes may not show up there.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
